services:
  nextjs:
    build: .
    ports:
      - "5173:3000"
    environment:
      NODE_ENV: production
    networks:
      - xarvis_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`www.xpan9.tech`)"
      - "traefik.http.routers.portfolio.entrypoints=web,websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
networks:
  xarvis_backend:
    external: true
    name: xarvis_backend
