version: '3.8'
services:
  nextjs:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --port 5173"
    environment:
      - NODE_ENV=development
